const LOGIN = 'LOGIN';
const SIGNUP = 'SIGNUP';
const NEW_EMPLOYEE = 'NEW_EMPLOYEE';
const SIGNUP_ERROR = 'SIGNUP_ERROR';
const LOGIN_ERROR = 'LOGIN_ERROR';
const NEW_EMPLOYEE_ERROR = 'NEW_EMPLOYEE_ERROR';
const CREATE_BANK_ACCOUNT = 'CREATE_BANK_ACCOUNT';
const CREATE_BANK_ACCOUNT_ERROR = 'CREATE_BANK_ACCOUNT_ERROR';
const GET_TRANSACTION_HISTORY = 'GET_TRANSACTION_HISTORY';
const TRANSACTION_HISTORY_ERROR = 'TRANSACTION_HISTORY_ERROR';
const GET_ACCOUNT_BY_OWNER_ID = 'GET_ACCOUNT_BY_OWNER_ID';
const GET_ACCOUNT_BY_OWNER_ID_ERROR = 'GET_ACCOUNT_BY_OWNER_ID_ERROR';
const GET_ALL_ACCOUNTS = 'GET_ALL_ACCOUNTS';
const GET_ALL_ACCOUNTS_ERROR = 'GET_ALL_ACCOUNTS_ERROR';
const DELETE_ACCOUNTS = 'DELETE_ACCOUNTS';
const DELETE_ACCOUNTS_ERROR = 'DELETE_ACCOUNTS_ERROR';
const ACTIVATE_AND_DEACTIVATE_ACCOUNTS = 'ACTIVATE_AND_DEACTIVATE_ACCOUNTS';
const ACTIVATE_AND_DEACTIVATE_ACCOUNTS_ERROR = 'ACTIVATE_AND_DEACTIVATE_ACCOUNTS_ERROR';
const DEBIT = 'DEBIT';
const DEBIT_ERROR = 'DEBIT_ERROR';
const CREDIT = 'CREDIT';
const CREDIT_ERROR = 'CREDIT_ERROR';

export {
  LOGIN,
  SIGNUP,
  NEW_EMPLOYEE,
  NEW_EMPLOYEE_ERROR,
  SIGNUP_ERROR,
  LOGIN_ERROR,
  CREATE_BANK_ACCOUNT,
  CREATE_BANK_ACCOUNT_ERROR,
  GET_TRANSACTION_HISTORY,
  TRANSACTION_HISTORY_ERROR,
  GET_ACCOUNT_BY_OWNER_ID,
  GET_ACCOUNT_BY_OWNER_ID_ERROR,
  GET_ALL_ACCOUNTS,
  GET_ALL_ACCOUNTS_ERROR,
  DELETE_ACCOUNTS,
  DELETE_ACCOUNTS_ERROR,
  ACTIVATE_AND_DEACTIVATE_ACCOUNTS,
  ACTIVATE_AND_DEACTIVATE_ACCOUNTS_ERROR,
  DEBIT,
  DEBIT_ERROR,
  CREDIT,
  CREDIT_ERROR,
};
